Fixed IllegalStateException in select that concurrently selects, which was due a problem with Job concurrent cancel and dispose of handle. The bug was introduced by addition of Cancelling state for a Job.
Original stack trace in select was:
java.lang.IllegalStateException: Check failed.
	at kotlinx.coroutines.experimental.internal.LockFreeLinkedListNode.remove(LockFreeLinkedList.kt:236)
	at kotlinx.coroutines.experimental.JobSupport.removeNode$kotlinx_coroutines_core(Job.kt:734)
	at kotlinx.coroutines.experimental.JobNode.dispose(Job.kt:995)
	at kotlinx.coroutines.experimental.selects.SelectBuilderImpl.initCancellability(Select.kt:294)
	at kotlinx.coroutines.experimental.selects.SelectBuilderImpl.getResult(Select.kt:273)